# Generated by Django 4.2.16 on 2026-09-09 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Institución educativa a la que pertenece el usuario.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='institutions.institution', verbose_name='institución'),
        ),
    ]
