# Generated by Django 4.2.16 on 2026-09-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_align_database_design"),
        ("users", "0002_usuario_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                db_column="institucion_id",
                help_text="Institución educativa a la que pertenece el usuario.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="institutions.institution",
                verbose_name="institución",
            ),
        ),
    ]
