# Generated by Django 4.2.16 on 2026-09-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del colegio o institución educativa.', max_length=200, verbose_name='nombre de la institución')),
                ('codigo_nit', models.CharField(help_text='Identificador único de la institución (NIT, código DANE u otro). No puede repetirse en el sistema.', max_length=20, unique=True, verbose_name='NIT / código de institución')),
                ('direccion', models.CharField(help_text='Dirección física de la institución.', max_length=300, verbose_name='dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='ciudad')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar impide el acceso de todos sus usuarios sin borrar registros.', verbose_name='activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
            ],
            options={
                'verbose_name': 'institución',
                'verbose_name_plural': 'instituciones',
                'db_table': 'instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(fields=('codigo_nit',), name='uq_institucion_codigo_nit'),
        ),
    ]
