# Generated by Django 4.2.16 on 2026-08-29 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID público generado automáticamente. Permite al denunciante consultar el estado de su reporte de forma anónima.', unique=True, verbose_name='código de seguimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'db_table': 'reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
