# Generated by Django 4.2.16 on 2026-09-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_align_database_design'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=50, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='institutions.institution', verbose_name='institución'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='nivel_riesgo',
            field=models.CharField(default='NO_EVALUADO', max_length=50, verbose_name='nivel de riesgo'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo_incidente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tipo de incidente'),
        ),
    ]
