# Generated by Django 4.2.16 on 2026-09-20 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institutions", "0002_align_database_design"),
        ("reports", "0002_reporte_descripcion_reporte_estado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoAgresion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=30, unique=True, verbose_name="código"),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "tipo de agresión",
                "verbose_name_plural": "tipos de agresión",
                "db_table": "tipos_agresion",
            },
        ),
        migrations.RemoveField(
            model_name="reporte",
            name="nivel_riesgo",
        ),
        migrations.RemoveField(
            model_name="reporte",
            name="tipo_incidente",
        ),
        migrations.AddField(
            model_name="reporte",
            name="acepta_revelar_identidad",
            field=models.BooleanField(
                default=False, verbose_name="acepta revelar identidad"
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="evidencia_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="URL de evidencia"
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="frecuencia",
            field=models.CharField(
                default="", max_length=100, verbose_name="frecuencia"
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="grado_victima",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="grado de la víctima"
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="involucrados_grado",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="grado de involucrados",
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="involucrados_tipo",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="tipo de involucrados",
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="medio_contacto_victima",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="medio contacto"
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="nivel_riesgo_confirmado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BAJO", "Bajo"),
                    ("MEDIO", "Medio"),
                    ("ALTO", "Alto"),
                    ("CRITICO", "Crítico"),
                ],
                max_length=20,
                null=True,
                verbose_name="nivel de riesgo confirmado",
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="nivel_riesgo_predicho",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BAJO", "Bajo"),
                    ("MEDIO", "Medio"),
                    ("ALTO", "Alto"),
                    ("CRITICO", "Crítico"),
                ],
                max_length=20,
                null=True,
                verbose_name="nivel de riesgo predicho",
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="nombre_contacto_victima",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="nombre contacto"
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="ubicacion",
            field=models.CharField(
                default="", max_length=100, verbose_name="ubicación"
            ),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="codigo_seguimiento",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="código de seguimiento",
            ),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="descripcion",
            field=models.TextField(default="", verbose_name="descripción"),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_REVISION", "En Revisión"),
                    ("ATENDIDO", "Atendido"),
                    ("DESCARTADO", "Descartado"),
                ],
                default="PENDIENTE",
                max_length=20,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                db_column="institucion_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportes",
                to="institutions.institution",
                verbose_name="institución",
            ),
        ),
        migrations.CreateModel(
            name="SeguimientoCaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(default="", verbose_name="observaciones"),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="estado anterior",
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(max_length=20, verbose_name="estado nuevo"),
                ),
                (
                    "fecha_atencion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de atención",
                    ),
                ),
                (
                    "orientador",
                    models.ForeignKey(
                        blank=True,
                        db_column="orientador_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="orientador",
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="reports.reporte",
                        verbose_name="reporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "seguimiento de caso",
                "verbose_name_plural": "seguimientos de casos",
                "db_table": "seguimiento_casos",
                "ordering": ["-fecha_atencion"],
            },
        ),
        migrations.AddField(
            model_name="reporte",
            name="tipos_agresion",
            field=models.ManyToManyField(
                blank=True,
                db_table="reportes_tipos_agresion",
                related_name="reportes",
                to="reports.tipoagresion",
                verbose_name="tipos de agresión",
            ),
        ),
    ]
