# Generated by Django 4.2.16 on 2026-09-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('categoria', models.CharField(choices=[('LINEA_DE_AYUDA', 'Línea de ayuda'), ('ORIENTACION', 'Orientación'), ('PROFESOR', 'Profesor de confianza'), ('OTRO', 'Otro')], default='OTRO', max_length=30, verbose_name='categoría')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('telefono', models.CharField(blank=True, default='', max_length=50, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, default='', max_length=254, verbose_name='correo')),
                ('url', models.URLField(blank=True, default='', verbose_name='enlace')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
                'db_table': 'recursos',
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
